version: '3'
services:
  alpha:
    container_name: alpha
    image: alpha
    ports:
      - 8082:80
  beta:
    container_name: beta
    image: beta
    ports:
      - 8081:80
  # nginx:
  #     container_name: nginx
  #     image: nginx-php
  #     depends_on:
  #     - beta
  #     - alpha
  #     ports:
  #       - 9000:80