version: '3'
services:
  alpha:
    container_name: alpha
    build: 
      context: ./alpha
      dockerfile: Dockerfile
    ports:
      - 8082:80
  beta:
    container_name: beta
    build: 
      context: ./beta
      dockerfile: Dockerfile
    ports:
      - 8081:80
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
    - beta
    - alpha
    ports:
      - 9000:80